
openvpn:
  port: 1194
  access_key: secret123
  destination: local  # 'local' or IP (listening on the same port)
  # destination: 192.68.0.20  # 'local' or IP (listening on the same port)
  protocol: tcp
  duration: 10  # Duration in seconds
  interface: eth0

# mysql:
#   port: 3306
#   access_key: secret123
#   destination: 192.68.0.30  # 'local' or IP (listening on the same port)
#   protocol: tcp
#   duration: 10  # Duration in seconds
#   interface: eth0
